// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "koredata": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/thefirstofthe300/kore-poc/koredata-goa/design
// --out=$(GOPATH)/src/github.com/thefirstofthe300/kore-poc/koredata-goa
// --version=v1.3.0

package app

// A quote from the user database (default view)
//
// Identifier: application/json; view=default
type JSON struct {
	// Quote
	Quotes []*Quote `form:"Quotes,omitempty" json:"Quotes,omitempty" xml:"Quotes,omitempty"`
}
