// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "koredata": Application User Types
//
// Command:
// $ goagen
// --design=github.com/hegemone/kore-poc/koredata-goa/design
// --out=$(GOPATH)/src/github.com/hegemone/kore-poc/koredata-goa
// --version=v1.3.1

package app

// All suggestions for a given user ID
type suggestion struct {
	// The ID of the show
	ShowID *string `form:"ShowID,omitempty" json:"ShowID,omitempty" xml:"ShowID,omitempty"`
	// Identity of suggester
	Suggester *string `form:"Suggester,omitempty" json:"Suggester,omitempty" xml:"Suggester,omitempty"`
	// The suggested title
	Title *string `form:"Title,omitempty" json:"Title,omitempty" xml:"Title,omitempty"`
}

// Publicize creates Suggestion from suggestion
func (ut *suggestion) Publicize() *Suggestion {
	var pub Suggestion
	if ut.ShowID != nil {
		pub.ShowID = ut.ShowID
	}
	if ut.Suggester != nil {
		pub.Suggester = ut.Suggester
	}
	if ut.Title != nil {
		pub.Title = ut.Title
	}
	return &pub
}

// All suggestions for a given user ID
type Suggestion struct {
	// The ID of the show
	ShowID *string `form:"ShowID,omitempty" json:"ShowID,omitempty" xml:"ShowID,omitempty"`
	// Identity of suggester
	Suggester *string `form:"Suggester,omitempty" json:"Suggester,omitempty" xml:"Suggester,omitempty"`
	// The suggested title
	Title *string `form:"Title,omitempty" json:"Title,omitempty" xml:"Title,omitempty"`
}
