# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Added at 2017-08-25 10:18:16 -0400 by nelsk:
gem "eventmachine", "~> 1.2"
